### PR TITLE
Link section padding [Fixes #71]

### LINKED ISSUE #71: [DESIGN BUG] spacing in let navigation
On the left navigation, the "sections" should have more space

Screen Shot 2022-11-30 11 14 17 AM

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Adds 4rem padding after link sections in LinksList left docs navigation

## Preview link
https://deploy-preview-106--melodious-puffpuff-8e1109.netlify.app/docs

## Related issue
- [Fixes #71]

### CODE REVIEW

**Review by nhsz — COMMENTED** [review]
These sections look weird, are we missing the section title maybe? or the item should be the title

Screen Shot 2022-12-02 at 14 02 48

Screen Shot 2022-12-02 at 14 03 18

Screen Shot 2022-12-02 at 14 03 30

**Comment by wackerow** [comment]
Not all links are nested within a section title.

Personally would advocate for scraping this. I think there is sufficient visual distinction with the section names being a different color, and the items within being indented. I'm not sure adding extra padding between sections is necessary. cc: @nloureiro

**Comment by nloureiro** [comment]
> Not all links are nested within a section title.
> 
> Personally would advocate for scraping this. I think there is sufficient visual distinction with the section names being a different color, and the items within being indented. I'm not sure adding extra padding between sections is necessary. cc: @nloureiro

I was testing this: (not final)
Screen Shot 2022-12-02 07 26 25 PM

Invert the colors > primary are always links and text color to the section

Assume that the sub-titles don't have links > as we did with the toggles > still need to confirm with @jmcook1186 this  


what do you think?

**Comment by wackerow** [comment]
@nloureiro I think that makes sense for the reasons you described... In the meantime, I'll at least trim down the gap size here so we can merge or close this PR. Can handle any color switching separately

**Comment by wackerow** [comment]
As of commit 4cde5bf
image

**Review by nhsz — APPROVED** [review]
Looking great, thx!

**Pull request merged**
