### PR TITLE
feat: add empty state for platforms without releases

### LINKED ISSUE #132: [UX IMPROVEMENT] empty tabs on the download table need a default message
to avoid having empty tabs on the download realises tabs, there  should be a default message for empty tabs

"No builds found"

and should have a min-height of 20rem/320px

For the text use the h4 style

Screen Shot 2022-12-06 02 29 44 PM

### PR DESCRIPTION
**Pull request by nhsz**
This PR adds an empty state for platforms without releases (currently only iOS dev builds). Fixes #132 

Screen Shot 2022-12-07 at 14 23 33

### CODE REVIEW

**Comment by wackerow** [comment]
image

Not sure how to test this.. Should this iOS view be empty then?

Looks like we lost our bottom border too with the style change

**Comment by wackerow** [comment]
image

Oops, nevermind, missed that this was just the develop builds... The empty state seems to be working, so just the border that seems to need fixing first.

**Comment by nhsz** [comment]
> image
> 
> Oops, nevermind, missed that this was just the develop builds... The empty state seems to be working, so just the border that seems to need fixing first.

Thx, fixed

**Review by wackerow — APPROVED** [review]
Looks good!

**Review by corwintines — APPROVED** [review]

**Pull request merged**
