### PR TITLE
Accessibility (a11y) clean up

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Adds a "skip to content" hidden button for keyboard navigation
- Adds missing aria-labels
- Adds `lang` attribute to `html` element

## Preview link
https://deploy-preview-138--melodious-puffpuff-8e1109.netlify.app/

## Issue
Homepage and downloads: existing layout scores 82% on a11y for light mode, and 85% on dark mode
image

## Screenshot
Homepage, downloads and docs pages: with this PR, scoring 100% for a11y on light and dark mode
image

## Todo
- [x] Improve docs pages
- [x] Mobile tune-up

### CODE REVIEW

**Comment by wackerow** [comment]
image

Added a patch for some warnings seen on the docs page, but still unable to fix this warning. I tried adding an aria label within the noted component, but that just raised more warnings. I'm not sure why we're getting this warning since there is text nested within this button, but at the same time we are using a structure of `button > div > a > a > p` which the browser is likely not loving.

image

If anyone has any suggestions

**Comment by wackerow** [comment]
This resolves with the `legacyBehavior` prop recently added to the `NextLink` component which also fixed the hydration warnings. 

Now getting 100% for desktop accessibility on both light and dark mode for `/`, `/docs` and `/downloads` pages.

Going to run mobile tests and add any easy fixes.

**Comment by wackerow** [comment]
Okay, getting 100% on mobile tests as well now. Ready for review.

**Review by nloureiro — APPROVED** [review]
Looking good on the design side!

**Review by nhsz — APPROVED** [review]
Great, LGTM! 🔥

**Pull request merged**
